select * from Amazon_sales

1. What is the total revenue generated by Amazon across all regions and countries?
Select round(sum(Total_Revenue), 2) as Total_revenue
from Amazon_sales


2. Which country has the highest total profit, and which one has the lowest?
Select country,Total_Profit from Amazon_sales
where Total_Profit = (select max(total_profit) from Amazon_sales)
or
Total_Profit = (select min(total_profit) from Amazon_sales)

3. What is the average unit price and unit cost of items sold in each region?select region, ROUND(AVG(unit_price), 2) as AVG_UNIT_PRICE, ROUND(AVG(UNIT_COST), 2) AS AVG_UNIT_COST From Amazon_salesgroup by Region4. Which item type has the highest sales volume (units sold) overall?select item_type from Amazon_saleswhere Units_Sold = (select MAX(Units_Sold) from Amazon_sales)5. How many orders were placed in each sales channel, and which channel had the most
orders?

select sales_channel, count(sales_channel) as Total_orders from Amazon_sales
group by Sales_Channel
order by Total_orders desc

6. What is the distribution of order priority across all regions?select region, order_priority, count(*) as priority_count from Amazon_salesgroup by region, Order_Priorityorder by Region, Order_Priority7. What is the average shipping time (in days) for orders from each country?select country,avg(datediff(day, ship_date, order_date)) as avg_shipping_time from Amazon_salesgroup by Country8. How does the average total profit vary across different order priorities?select Order_Priority, ROUND(avg(total_profit), 2) as avg_total_profit from Amazon_salesgroup by Order_Priority9. Which month had the highest total revenue, and which had the lowest?select month(order_date) as month_ , Total_Revenue from Amazon_saleswhere Total_Revenue = (select(max(Total_Revenue)) from Amazon_sales)orTotal_Revenue = (select(min(Total_Revenue)) from Amazon_sales)